@startuml 자연어처리 분석 서비스
title 자연어처리 분석 서비스
start 
    : 자연어 입력 ;
    if (한글) then (Yes)
        : 문장 분리 ;
        repeat : 형태소 분석 ;
        : 구문 분석 ;
        : 의미 분석 ;
        repeat while (화용 분석) is (분석 \n 미완료) ;
        : 분석 결과 ;
    else (No)
        : 다국어 처리 불가 메세지 ;
    endif
end 
@enduml